# Generated by Django 2.2.6 on 2019-10-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_address_event_eventseries_participant_round_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Venue')),
            ],
            bases=('main.venue',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Participant')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_football.Stadium')),
            ],
            bases=('main.participant',),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('eventseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.EventSeries')),
                ('is_current', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_football.League')),
            ],
            bases=('main.eventseries',),
        ),
    ]
